version: '3'
services:
  elasticsearch:
    build: es
    volumes:
        - "./es/es-data:/usr/share/elasticsearch/data"
        - "./es/config:/usr/share/elasticsearch/config"
    ports:
        - 9200:9200
    expose:
        - 9300
  kibana:
    build: kibana
    links:
        - elasticsearch:elasticsearch
    ports:
        - 5601:5601

  flask:
    build: flask
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    volumes:
      - "./flask/src:/home/src"
